# Generated by Django 3.2.7 on 2021-10-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='athlete',
            name='contact_nb',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='athlete',
            name='email',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='athlete',
            name='injury',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='athlete',
            name='phone_nb',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
