# Generated by Django 3.2.7 on 2021-10-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_num', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('heatvalue', models.IntegerField()),
                ('workout_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workout')),
            ],
        ),
    ]
