# Generated by Django 3.2.7 on 2021-10-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211007_1637'),
        ('main', '0002_sensorreading_workout'),
    ]

    operations = [
    ]
