# Generated by Django 3.2.7 on 2021-10-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211011_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='auth_user',
        ),
    ]
